### ISSUE TITLE
Nope, this package do not work

### ISSUE THREAD

**Issue by garmoshka-mo** [tj/serve#58]
````
vagrant@precise32:~/repos/nemobile$ sudo npm install serve   
npm WARN package.json worker@0.0.1 No description
npm WARN package.json worker@0.0.1 No repository field.
npm WARN package.json worker@0.0.1 No README data
npm WARN package.json worker@0.0.1 No license field.
npm WARN prefer global serve@1.4.0 should be installed with -g
serve@1.4.0 node_modules/serve
├── commander@0.6.1
├── connect@2.3.9 (fresh@0.1.0, bytes@0.1.0, cookie@0.0.4, crc@0.2.0, qs@0.4.2, debug@2.2.0, send@0.0.3, formidable@1.0.11)
├── stylus@0.51.1 (css-parse@1.7.0, mkdirp@0.3.5, debug@2.2.0, glob@3.2.11, source-map@0.1.43, sax@0.5.8)
├── jade@1.11.0 (character-parser@1.2.1, void-elements@2.0.1, commander@2.6.0, mkdirp@0.5.1, jstransformer@0.0.2, with@4.0.3, constantinople@3.0.1, clean-css@3.3.6, uglify-js@2.4.23, transformers@2.1.0)
└── less-middleware@2.0.1 (node.extend@1.1.5, mkdirp@0.5.1, less@2.4.0)
vagrant@precise32:~/repos$ node serve
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/vagrant/repos/serve'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
````

**Comment by Calvein** [comment]
You're using it incorrectly.

To install it, do `npm install -g serve`, not `sudo npm install serve`
To use it, do `serve`, not `node serve`

Read the readme next time https://github.com/tj/serve/blob/master/Readme.md

**Comment by garmoshka-mo** [comment]
ah, thanx!
